version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  # The test job
  build:
    working_directory: ~/my-app-Trener
    docker:
      - image: circleci/node:10-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout:
          path: ~/my-app-Trener
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          key: my-app-Trener-{{ .Branch }}-{{ checksum "package-lock.json" }}
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: my-app-Trener-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      # Test the source code
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI